%% ========================================================================
%  FILE 7: update_visualization.m
%  Updates all visual elements during simulation
%% ========================================================================

function update_visualization(env, figures, uav, sensors, config, timeElapsed, pathProgress)
    % Updates all graphical elements
    
    uavPos = uav.getPosition();
    
    %% Update UAV position in 3D
    set(env.uavPlot, 'XData', uavPos(1)+env.uavX, ...
                     'YData', uavPos(2)+env.uavY, ...
                     'ZData', uavPos(3)+env.uavZ);
    
    set(env.uavBody, 'XData', uavPos(1), ...
                     'YData', uavPos(2), ...
                     'ZData', uavPos(3));
    
    %% Update camera FOV cone
    if config.SHOW_FOV && isfield(env, 'cameraFOV')
        conePts = [uavPos(1) + env.cameraRadius*cos(env.cameraTheta); ...
                   uavPos(2) + env.cameraRadius*sin(env.cameraTheta); ...
                   zeros(1, 20)];
        
        % Flatten the data into vectors
        xData = [uavPos(1)*ones(1,20), conePts(1,:)];
        yData = [uavPos(2)*ones(1,20), conePts(2,:)];
        zData = [uavPos(3)*ones(1,20), conePts(3,:)];
        
        set(env.cameraFOV, 'XData', xData, 'YData', yData, 'ZData', zData);
    end
    
    %% Update flight trail
    if config.SHOW_TRAIL
        env.trailData = [env.trailData; uavPos];
        if size(env.trailData, 1) > config.TRAIL_LENGTH
            env.trailData = env.trailData(end-config.TRAIL_LENGTH+1:end, :);
        end
        set(env.trailPlot, 'XData', env.trailData(:,1), ...
                           'YData', env.trailData(:,2), ...
                           'ZData', env.trailData(:,3));
    end
    
    %% Update top-down view
    set(env.uavDot, 'XData', uavPos(1), 'YData', uavPos(2));
    set(env.trailTop, 'XData', env.trailData(:,1), 'YData', env.trailData(:,2));
    
    %% Update real-time data display with comprehensive parameters
    dataStr = sprintf([...
        '╔═══════════════════════════════════╗\n' ...
        '║   REAL-TIME UAV DATA & ANALYSIS   ║\n' ...
        '╠═══════════════════════════════════╣\n' ...
        '║ Time: %6.1f s                     ║\n' ...
        '║ Battery: %5.1f%%                  ║\n' ...
        '╠═══════════════════════════════════╣\n' ...
        '║ UAV POSITION                      ║\n' ...
        '║ X: %6.1f m  Y: %6.1f m            ║\n' ...
        '║ Z: %6.1f m (AGL)                  ║\n' ...
        '╠═══════════════════════════════════╣\n' ...
        '║ SCAN PROGRESS                     ║\n' ...
        '║ Coverage: %5.1f%%                 ║\n' ...
        '║ Area: %6.0f / %d m²               ║\n' ...
        '╠═══════════════════════════════════╣\n' ...
        '║ VEGETATION INDICES                ║\n' ...
        '║ NDVI: %5.3f (%s)                  ║\n' ...
        '║ LAI: %5.2f                        ║\n' ...
        '║ Greenness: %5.1f%%                ║\n' ...
        '╠═══════════════════════════════════╣\n' ...
        '║ STRESS DETECTION                  ║\n' ...
        '║ Water: %5.1f%%                    ║\n' ...
        '║ Pest: %5.1f%%                     ║\n' ...
        '║ Nutrient: %5.1f%%                 ║\n' ...
        '║ Thermal: %5.1f%%                  ║\n' ...
        '╠═══════════════════════════════════╣\n' ...
        '║ GROWTH STATUS                     ║\n' ...
        '║ Stage: %-18s                      ║\n' ...
        '║ Canopy: %5.1f%%                   ║\n' ...
        '║ Height: %5.0f cm                  ║\n' ...
        '╠═══════════════════════════════════╣\n' ...
        '║ STATUS: %-26s                     ║\n' ...
        '╚═══════════════════════════════════╝'], ...
        timeElapsed, uav.getBattery(), ...
        uavPos(1), uavPos(2), uavPos(3), ...
        pathProgress, sensors.getScannedArea(), config.FIELD_SIZE^2, ...
        sensors.getNDVI(), sensors.classifyHealth(), ...
        sensors.getLAI(), sensors.getGreenness(), ...
        sensors.getWaterStress(), sensors.getPestAttack(), ...
        sensors.getNutrientDeficiency(), sensors.getThermalStress(), ...
        sensors.getGrowthStage(), sensors.getCanopyDensity(), ...
        sensors.getPlantHeight(), sensors.getHealthStatus());
    
    set(env.dataText, 'String', dataStr);
    
    %% Update 3D view title
    title(figures.ax3D, sprintf('3D UAV Flight Simulation - %.1f%% Complete | NDVI: %.3f', ...
          pathProgress, sensors.getNDVI()), 'FontSize', 14, 'FontWeight', 'bold');
    
    %% Auto-rotate view if enabled
    if config.AUTO_ROTATE && mod(round(timeElapsed*100), 10) == 0
        currentView = get(figures.ax3D, 'View');
        view(figures.ax3D, currentView(1) + config.ROTATION_SPEED, currentView(2));
    end
    
    %% Force graphics update
    drawnow;
end